// Product data for the Free Online Store Template
export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  discountPrice?: number;
  image: string;
  category: string;
  stock: number;
  rating: number;
  reviews: number;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and superior sound quality. Perfect for music lovers and professionals.",
    price: 199.99,
    discountPrice: 149.99,
    image: "/images/headphones.jpg",
    category: "Electronics",
    stock: 15,
    rating: 4.5,
    reviews: 128,
  },
  {
    id: 2,
    name: "Leather Laptop Bag",
    description: "Stylish and durable leather laptop bag designed for professionals. Fits laptops up to 15 inches with additional compartments.",
    price: 89.99,
    discountPrice: 69.99,
    image: "/images/laptop-bag.jpg",
    category: "Accessories",
    stock: 25,
    rating: 4.3,
    reviews: 86,
  },
  {
    id: 3,
    name: "Smart Watch",
    description: "Advanced smartwatch with health monitoring, GPS tracking, and smartphone integration. Water-resistant design with long battery life.",
    price: 249.99,
    discountPrice: 199.99,
    image: "/images/smartwatch.jpg",
    category: "Electronics",
    stock: 12,
    rating: 4.7,
    reviews: 215,
  },
  {
    id: 4,
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt available in multiple colors. Ethically produced with fair trade certification.",
    price: 29.99,
    discountPrice: 24.99,
    image: "/images/tshirt.jpg",
    category: "Clothing",
    stock: 50,
    rating: 4.2,
    reviews: 67,
  },
  {
    id: 5,
    name: "Stainless Steel Water Bottle",
    description: "Eco-friendly insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours. BPA-free with lifetime warranty.",
    price: 34.99,
    discountPrice: 29.99,
    image: "/images/water-bottle.jpg",
    category: "Accessories",
    stock: 100,
    rating: 4.6,
    reviews: 342,
  },
  {
    id: 6,
    name: "Yoga Mat",
    description: "Non-slip, eco-friendly yoga mat with extra cushioning for joint support. Includes carrying strap and alignment markers.",
    price: 49.99,
    discountPrice: 39.99,
    image: "/images/yoga-mat.jpg",
    category: "Fitness",
    stock: 30,
    rating: 4.4,
    reviews: 156,
  },
  {
    id: 7,
    name: "Standing Desk Converter",
    description: "Adjustable height desk converter that transforms any regular desk into a standing desk. Spacious work surface with smooth transition.",
    price: 299.99,
    discountPrice: 249.99,
    image: "/images/standing-desk.jpg",
    category: "Furniture",
    stock: 8,
    rating: 4.5,
    reviews: 93,
  },
  {
    id: 8,
    name: "Ergonomic Office Chair",
    description: "Comfortable office chair with lumbar support, adjustable armrests, and breathable mesh back. Designed for all-day comfort.",
    price: 399.99,
    discountPrice: 349.99,
    image: "/images/office-chair.jpg",
    category: "Furniture",
    stock: 5,
    rating: 4.6,
    reviews: 127,
  },
  {
    id: 9,
    name: "Denim Jacket",
    description: "Classic denim jacket with modern fit and sustainable production. Features multiple pockets and adjustable waist.",
    price: 79.99,
    discountPrice: 64.99,
    image: "/images/denim-jacket.jpg",
    category: "Clothing",
    stock: 20,
    rating: 4.3,
    reviews: 84,
  },
  {
    id: 10,
    name: "Camera Lens Kit",
    description: "Professional camera lens kit with multiple focal lengths. Compatible with most DSLR and mirrorless cameras.",
    price: 599.99,
    discountPrice: 499.99,
    image: "/images/camera-lens.jpg",
    category: "Electronics",
    stock: 3,
    rating: 4.8,
    reviews: 42,
  },
  {
    id: 11,
    name: "Sunglasses",
    description: "UV-protective polarized sunglasses with lightweight frame and scratch-resistant lenses. Includes protective case.",
    price: 59.99,
    discountPrice: 49.99,
    image: "/images/sunglasses.jpg",
    category: "Accessories",
    stock: 40,
    rating: 4.4,
    reviews: 178,
  },
  {
    id: 12,
    name: "Coffee Maker",
    description: "Programmable coffee maker with thermal carafe, adjustable strength settings, and automatic shut-off. Makes up to 12 cups.",
    price: 129.99,
    discountPrice: 99.99,
    image: "/images/coffee-maker.jpg",
    category: "Home",
    stock: 15,
    rating: 4.5,
    reviews: 267,
  },
  {
    id: 13,
    name: "Phone Charger",
    description: "Fast-charging wall adapter with multiple USB ports and universal compatibility. Includes safety features and compact design.",
    price: 29.99,
    discountPrice: 19.99,
    image: "/images/charger.jpg",
    category: "Electronics",
    stock: 75,
    rating: 4.2,
    reviews: 312,
  },
  {
    id: 14,
    name: "Smart Home Hub",
    description: "Central control hub for all your smart home devices. Compatible with major brands and voice assistants.",
    price: 149.99,
    discountPrice: 119.99,
    image: "/images/smart-hub.jpg",
    category: "Electronics",
    stock: 10,
    rating: 4.3,
    reviews: 96,
  },
  {
    id: 15,
    name: "Backpack",
    description: "Durable backpack with laptop compartment, water bottle holder, and multiple organizational pockets. Comfortable padded straps.",
    price: 79.99,
    discountPrice: 64.99,
    image: "/images/backpack.jpg",
    category: "Accessories",
    stock: 25,
    rating: 4.5,
    reviews: 189,
  }
];

// Categories
export const categories = [
  "All",
  "Electronics",
  "Clothing",
  "Accessories",
  "Furniture",
  "Fitness",
  "Home"
];
